# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Research',  url: 'research'}
- {name: 'Projects',       url: 'campaigns'}
- {name: 'Publications',      url: 'publications'}
- {name: 'Teaching',      url: 'teaching'}
- {name: 'About',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link:  'https://github.com/kdlamb'}
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/kara-diane-lamb/'}
- {icon: 'twitter', link:   'https://bsky.app/profile/karadlamb.bsky.social'}
- {icon: 'envelope', link:   'mailto:kl3231@columbia.edu'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
